#!/bin/bash
set -eux
source $(dirname $0)/../tripleorc

sudo apt-get install --yes python-lxml python-libvirt libvirt-bin qemu-system

ls $dib_root       || git clone $dib_repo $dib_root
ls $incubator_root || git clone $incubator_repo $incubator_root
ls $bm_poseur_root || git clone $bm_poseur_repo $bm_poseur_root

grep bmposeur /etc/network/interfaces || sudo $bm_poseur_root/bm_poseur --bridge-ip=none create-bridge
sudo service libvirt-bin restart


mkdir -p $images
