#!/bin/bash
set -eux
source $(dirname $0)/../tripleorc

DEBIAN_FRONTEND=noninteractive sudo apt-get install --yes python-lxml python-libvirt libvirt-bin qemu-system qemu-kvm

ls $dib_root       || git clone -b $dib_branch $dib_repo $dib_root
ls $incubator_root || git clone -b $incubator_branch $incubator_repo $incubator_root
ls $bm_poseur_root || git clone -b $bm_poseur_branch $bm_poseur_repo $bm_poseur_root

grep bmposeur /etc/network/interfaces || sudo $bm_poseur_root/bm_poseur --bridge-ip=none create-bridge
sudo service libvirt-bin restart

mkdir -p $tripleo

mkdir -p $images
