#!/bin/bash
source $(dirname $0)/../tripleorc
source $root/lib/functions

cmd=$(cat <<eof
source devstack/openrc &&
PATH=\$PATH:/opt/stack/diskimage-builder/bin/ \
incubator/scripts/deploystack --kernel demo-initrd --initrd demo-initrd incubator/stacks/keystone.yaml --extra base stackuser
eof
)

run_in_bootstrap "$cmd"

