#!/bin/bash
set -eux

export root="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $root/localrc

export git_root=${git_root:-$HOME/tripleo}

# check out code here
export tripleo=$git_root

# store images here
export images=${images:-$tripleo/images}

export num_bm_nodes=${num_bm_nodes:-"3"}

# include these elements in all images
export always_elements=$always_elements

export always_packages=$always_packages

export dib_root=$tripleo/diskimage-builder
export dib_repo="git@github.com:stackforge/diskimage-builder.git"

export incubator_root=$tripleo/incubator
export incubator_repo="git@github.com:tripleo/incubator.git"

export bm_poseur_root=$tripleo/bm_poseur
export bm_poseur_repo="git@github.com:tripleo/bm_poseur.git"

export bin=$root/bin
